### ISSUE TITLE
Make currency symbol customisable

### ISSUE THREAD

**Issue by ctgreybeard** [malnvenshorn/OctoPrint-FilamentManager#1]
Just a cosmetic thing but we use $ here in the US. Could you use the locale currency symbol?

**Comment by malnvenshorn** [comment]
The issue is I don't know if there is a way to get the currency symbol for the browser language and I don't want to create a list which maps the language codes to the currency symbols, because in Europe alone there exists more than 20 different currencies. Of cause I could add an input field to make the symbol configurable, but I'm not enthusiastic about that idea either. I think it doesn't matter what currency symbol is shown, because it's just an input field in the settings. 

I'm still open for suggestions. Maybe I'm adding a universal symbol for money.

**Comment by Mavyre** [comment]
The best option is to let the user input its own Character as the currency. It'd be the same as adding the universal symbol.

**Comment by ctgreybeard** [comment]
I'll take a look at it. This clearly isn't a critical issue so it doesn't need immediate attention. If I find an answer I'll post back.

**Comment by peepsnet** [comment]
where are the files on the RPI(OctoPI) I can just edit it for now??

**Comment by ctgreybeard** [comment]
The character is in the file templates/filamentmanager_spooldialog.jinja2 around line 42.

If you change it manually you will need to re-change it after every release.

**Comment by peepsnet** [comment]
Thanks.

**Comment by peepsnet** [comment]
Where in the file structure of the RPI is that file?? I cannot find it

**Comment by peepsnet** [comment]
I found it burried in
`/home/pi/oprint/lib/python2.7/site-packages/`

**Comment by cbale2000** [comment]
Other cost calculator plug-ins just have an open field where you can enter any symbol (though many have it set to Euro by default). I'll second this feature request.

**Comment by malnvenshorn** [comment]
Currency symbol can be customized in version 0.2.0
