### ISSUE TITLE
[Request] Nozzle manager

### ISSUE THREAD

**Issue by JanneMantyharju** [malnvenshorn/OctoPrint-FilamentManager#119]
I often use my printer remotely and this plugin is great to help me remember which spools are installed. I'd like to see a feature or fork of this plugin (Nozzle manager?) to keep track of installed nozzles and their usage times (or printed filament per nozzle)

**Comment by malnvenshorn** [comment]
I think this is the wrong place for you request. My plugin is for managing your spool inventory, especially to keep track of the remaining filament on each spool. It's not meant to keep track of the currently installed nozzle or to provide some kind of history ("printed filament per nozzle").

I'm closing this ticket because I'm not going to implement your suggested features. Of course everyone can use this plugin as some kind of blueprint to develop a plugin which fits your needs.
