### ISSUE TITLE
sort by spool cost

### ISSUE THREAD

**Issue by sebaschn** [malnvenshorn/OctoPrint-FilamentManager#13]
hey there,

i'm very impressed by your plugin. BIG thanks!!

how about beeing able to sort the spools by it's cost? since i'm typing the value in, it's a waste i can't sort by it.

regards :-)

**Comment by malnvenshorn** [comment]
I'm glad that you like this plugin. The reason for the spool cost is that it's used by my [cost estimation plugin](https://github.com/malnvenshorn/OctoPrint-CostEstimation). Because of the limited space not all columns are shown in the table (including the cost) and I'm not sure if it would make sense to be able to sort the entries by a property which is not shown.
