### ISSUE TITLE
Empy spool weight

### ISSUE THREAD

**Issue by dipusone** [malnvenshorn/OctoPrint-FilamentManager#19]
Could be helpful in the filament profile a field where to store the wight of an empty spool for reference.
So, even if you do not keep track from the start of the weight you could retrieve the amount of remaining filament.

**Comment by malnvenshorn** [comment]
I think it doesn't make sense to put this information in the filament profiles, because some vendors offer different spool size of the same filament (e.g. 1000g and 2500g). Therefore you would need two separate profiles for those spools which is something I want to avoid. Another point is that you need this information only once for your opened spools.
