### ISSUE TITLE
Automatically pause the print if filament runs out

### ISSUE THREAD

**Issue by KD7LRJ** [malnvenshorn/OctoPrint-FilamentManager#2]
Rather than disallowing printing with too little filament remaining, how about the ability to pause when reaching a threshold? It could also trigger other plug-ins (I use OcotoSlack) to let you know to change the filament. This would be great for using up those pesky end-of-spool remnants on items are functional instead of aesthetic,

**Comment by malnvenshorn** [comment]
Printing is not prevented if there is not enough filament left on the spool, the plugin only shows a warning message.

The idea to automatically pause the print if the filament runs out crossed my mind too and it might be integrated in a future release. But I don't think that I'm going to integrate notification plugins. The reason is that there are quite a lot plugins of that kind, e.g. OctoSlack, Email Notifier, Pushbullet, Telegram, just to mention a few.
