### ISSUE TITLE
[Request] end filament notification

### ISSUE THREAD

**Issue by DavideCenc** [malnvenshorn/OctoPrint-FilamentManager#59]
good job! works well.
Is it possible to insert a notification (eg pushbullet or pushetta) that warns when the printer is in pauses because it has terminated the filament? thank you

**Comment by malnvenshorn** [comment]
You should contact the developer of the notification plugin to integrate such a feature. I'm not going to implement any kind of notification, because I don't want to maintain a huge amount of notification services. If I start to provide support for pushbullet there will be requests for e.g. slack, telegram, email, etc.
